/* GRANDPRIDE & GRANDLAB — SHARED STAFF LIST (generated by Staff Manager) */
var ALL_APPS = ['attendance','tasklog','joborder','academy','dutyboard','stock'];

var STAFF_SEED = [
  { username:'admin', name:'Administrator', role:'Admin', canPostNotice:true, apps:ALL_APPS.concat(['mia']) },
  { username:'juinnie', name:'Juinnie Thor', role:'HOD', company:'Grandpride', title:'Managing Director', birthday:'1995-03-16', reportsTo:['role:CEO'], canPostNotice:true, apps:ALL_APPS.concat(['mia','gpagreement','gpchecklist','gpdaily','gpappt','gprecord']) },
  { username:'liam', name:'Liam Ong', role:'HOD', company:'Grandpride', title:'CEO', birthday:'1992-06-10', canPostNotice:true, apps:ALL_APPS.concat(['mia','gpagreement','gpchecklist','gpdaily','gpappt','gprecord']) },
  { username:'jimmy', name:'Jimmy Kuek', role:'Manager', company:'Grandpride', title:'Manager', birthday:'1994-05-31', reportsTo:['role:CEO','role:Managing Director'], canPostNotice:true, apps:ALL_APPS.concat(['mia','jobboard','gpagreement','gpchecklist','gpdaily','gpappt','gprecord']) },
  { username:'iffat', name:'Iffat', role:'Staff', company:'Grandpride', title:'Videographer', reportsTo:['juinnie','liam','jimmy'], apps:['attendance','tasklog'] },
  { username:'iffah', name:'Iffah', role:'Finance', company:'Grandpride', title:'Finance', reportsTo:['role:CEO','role:Managing Director'], apps:['attendance','tasklog','joborder','stock'] },
  { username:'alex', name:'Alex', role:'Staff', company:'Grandpride', title:'Business Development Executive', reportsTo:['juinnie','liam','jimmy'], apps:['attendance','tasklog','joborder','mia','jobboard'] },
  { username:'iqa', name:'Iqa', role:'Receptionist', company:'Grandpride', title:'Receptionist', reportsTo:['juinnie','jimmy','iffah'], canPostNotice:true, apps:['attendance','tasklog','joborder','dutyboard','stock','mia','jobboard'] },
  { username:'shafiq', name:'Shafiq', role:'Staff', company:'Grandlab', title:'QC Person', birthday:'2001-10-07', reportsTo:['jimmy','iqa'], apps:['attendance','joborder','academy','dutyboard','stock','jobboard'] },
  { username:'mior', name:'Mior', role:'Staff', company:'Grandpride', title:'Operation Executive', reportsTo:['role:CEO','role:Managing Director','juinnie','liam'], canPostNotice:true, apps:['attendance','tasklog','gpagreement','gpchecklist','gpdaily','gpappt','gprecord'] },
];
